var searchData=
[
  ['scope_0',['Scope',['../md_docs_2pages_2execution.html#autotoc_md59',1,'Async Scope'],['../md_docs_2pages_2execution.html#autotoc_md63',1,'Counting Scope']]],
  ['scope_20abstraction_1',['Benefits of Async Scope Abstraction',['../md_docs_2pages_2execution.html#autotoc_md64',1,'']]],
  ['sender_2',['Type Erased Sender',['../md_docs_2pages_2execution.html#autotoc_md65',1,'']]],
  ['sender_20fails_3',['Case 2: Creating the Type-Erased Sender Fails',['../md_docs_2pages_2execution.html#autotoc_md69',1,'']]],
  ['sending_20and_20receiving_20messages_4',['Sending and Receiving Messages',['../md_docs_2pages_2ipc.html#autotoc_md82',1,'']]],
  ['sending_20messages_5',['Sending Messages',['../md_docs_2pages_2ipc.html#autotoc_md80',1,'']]],
  ['sequence_6',['set_next() Allows the Receiver to Communicate Back to the Sequence',['../md_docs_2pages_2execution.html#autotoc_md45',1,'']]],
  ['sequence_20life_20time_20model_7',['Async Sequence Life Time Model',['../md_docs_2pages_2execution.html#autotoc_md46',1,'']]],
  ['sequence_20model_8',['Drawbacks of the Async Sequence Model',['../md_docs_2pages_2execution.html#autotoc_md50',1,'']]],
  ['sequences_9',['Sequences',['../md_docs_2pages_2execution.html#autotoc_md43',1,'Async Sequences'],['../md_docs_2pages_2execution.html#autotoc_md47',1,'Lockstep Sequences']]],
  ['sequences_10',['How do completion signatures work with sequences?',['../md_docs_2pages_2execution.html#autotoc_md48',1,'']]],
  ['serialization_11',['Serialization',['../md_docs_2pages_2serialization.html',1,'md_docs_2pages_2library__component__overview']]],
  ['serialization_20formats_12',['Custom Serialization Formats',['../md_docs_2pages_2serialization.html#autotoc_md94',1,'']]],
  ['set_5fnext_13',['Who calls set_next()?',['../md_docs_2pages_2execution.html#autotoc_md44',1,'']]],
  ['set_5fnext_20allows_20the_20receiver_20to_20communicate_20back_20to_20the_20sequence_14',['set_next() Allows the Receiver to Communicate Back to the Sequence',['../md_docs_2pages_2execution.html#autotoc_md45',1,'']]],
  ['shared_20ownership_15',['Shared Ownership',['../md_docs_2pages_2bytes.html#autotoc_md27',1,'']]],
  ['shell_16',['Nix Dev Shell',['../md_docs_2pages_2developing.html#autotoc_md30',1,'']]],
  ['signatures_20work_20with_20sequences_17',['How do completion signatures work with sequences?',['../md_docs_2pages_2execution.html#autotoc_md48',1,'']]],
  ['spawn_18',['Spawn',['../md_docs_2pages_2execution.html#autotoc_md61',1,'']]],
  ['spawn_20future_19',['Spawn Future',['../md_docs_2pages_2execution.html#autotoc_md62',1,'']]],
  ['stack_20',['The Async Call Stack',['../md_docs_2pages_2execution.html#autotoc_md52',1,'']]],
  ['standard_20c_20allocators_21',['Problem with Standard C++ Allocators',['../md_docs_2pages_2allocator.html#autotoc_md7',1,'']]],
  ['state_20fails_22',['Case 3: Creating the Type-Erased Operation State Fails',['../md_docs_2pages_2execution.html#autotoc_md70',1,'']]],
  ['static_20reflection_23',['Static Reflection',['../md_docs_2pages_2static__reflection.html',1,'md_docs_2pages_2library__component__overview']]],
  ['storage_24',['Virtual Table Storage',['../md_docs_2pages_2type__erasure.html#autotoc_md116',1,'']]],
  ['store_25',['Type Erased Backing Store',['../md_docs_2pages_2bytes.html#autotoc_md26',1,'']]],
  ['summary_26',['Any Type Summary',['../md_docs_2pages_2type__erasure.html#autotoc_md119',1,'']]],
  ['synchronization_27',['Synchronization',['../md_docs_2pages_2ipc.html#autotoc_md87',1,'']]]
];
