var searchData=
[
  ['c_0',['Note on C++',['../md_docs_2pages_2static__reflection.html#autotoc_md98',1,'']]],
  ['c_20allocators_1',['Problem with Standard C++ Allocators',['../md_docs_2pages_2allocator.html#autotoc_md7',1,'']]],
  ['call_20stack_2',['The Async Call Stack',['../md_docs_2pages_2execution.html#autotoc_md52',1,'']]],
  ['calls_20set_5fnext_3',['Who calls set_next()?',['../md_docs_2pages_2execution.html#autotoc_md44',1,'']]],
  ['can_20be_20asynchronous_4',['Cleanup can be Asynchronous',['../md_docs_2pages_2execution.html#autotoc_md53',1,'']]],
  ['can_20be_20fallible_5',['Cleanup can be Fallible',['../md_docs_2pages_2execution.html#autotoc_md54',1,'']]],
  ['case_201_3a_20creating_20the_20type_20erased_20receiver_20fails_6',['Case 1: Creating the Type-Erased Receiver Fails',['../md_docs_2pages_2execution.html#autotoc_md68',1,'']]],
  ['case_202_3a_20creating_20the_20type_20erased_20sender_20fails_7',['Case 2: Creating the Type-Erased Sender Fails',['../md_docs_2pages_2execution.html#autotoc_md69',1,'']]],
  ['case_203_3a_20creating_20the_20type_20erased_20operation_20state_20fails_8',['Case 3: Creating the Type-Erased Operation State Fails',['../md_docs_2pages_2execution.html#autotoc_md70',1,'']]],
  ['categories_9',['Object Categories',['../md_docs_2pages_2type__erasure.html#autotoc_md118',1,'']]],
  ['class_10',['Using the IntrusiveList class',['../md_docs_2pages_2intrusive.html#autotoc_md76',1,'']]],
  ['cleanup_20can_20be_20asynchronous_11',['Cleanup can be Asynchronous',['../md_docs_2pages_2execution.html#autotoc_md53',1,'']]],
  ['cleanup_20can_20be_20fallible_12',['Cleanup can be Fallible',['../md_docs_2pages_2execution.html#autotoc_md54',1,'']]],
  ['cmake_13',['CMake',['../md_docs_2pages_2build.html#autotoc_md13',1,'Building with CMake'],['../md_docs_2pages_2build.html#autotoc_md15',1,'Consuming via CMake']]],
  ['cmake_20developer_20mode_14',['CMake Developer Mode',['../md_docs_2pages_2developing.html#autotoc_md32',1,'']]],
  ['commands_15',['Commands',['../md_docs_2pages_2build.html#autotoc_md17',1,'Install Commands'],['../md_docs_2pages_2build.html#autotoc_md16',1,'Manual Build Commands'],['../md_docs_2pages_2build.html#autotoc_md22',1,'Manual Build Commands']]],
  ['communicate_20back_20to_20the_20sequence_16',['set_next() Allows the Receiver to Communicate Back to the Sequence',['../md_docs_2pages_2execution.html#autotoc_md45',1,'']]],
  ['communication_17',['Inter-Process Communication',['../md_docs_2pages_2ipc.html',1,'md_docs_2pages_2library__component__overview']]],
  ['comparison_20with_20libunifex_20models_18',['Comparison with libunifex Models',['../md_docs_2pages_2execution.html#autotoc_md49',1,'']]],
  ['comparison_20with_20owning_20containers_19',['Comparison with Owning Containers',['../md_docs_2pages_2intrusive.html#autotoc_md73',1,'']]],
  ['completion_20',['Note for Auto-Completion',['../md_docs_2pages_2developing.html#autotoc_md31',1,'']]],
  ['completion_20signatures_20work_20with_20sequences_21',['How do completion signatures work with sequences?',['../md_docs_2pages_2execution.html#autotoc_md48',1,'']]],
  ['complex_20cpos_22',['Expressivity for complex CPOs',['../md_docs_2pages_2type__erasure.html#autotoc_md111',1,'']]],
  ['component_20overview_23',['Component Overview',['../md_docs_2pages_2library__component__overview.html',1,'Library Component Overview'],['../index.html#autotoc_md2',1,'Library Component Overview']]],
  ['concepts_24',['Universality with Concepts',['../md_docs_2pages_2type__erasure.html#autotoc_md108',1,'']]],
  ['conceptual_20example_25',['Conceptual Example',['../md_docs_2pages_2allocator.html#autotoc_md11',1,'']]],
  ['conceptual_20overview_26',['Conceptual Overview',['../md_docs_2pages_2execution.html#autotoc_md41',1,'Conceptual Overview'],['../md_docs_2pages_2ipc.html#autotoc_md79',1,'Conceptual Overview']]],
  ['concern_20with_20intrusive_20containers_27',['Main Concern with Intrusive Containers',['../md_docs_2pages_2intrusive.html#autotoc_md74',1,'']]],
  ['concerns_28',['Ergonomic Concerns',['../md_docs_2pages_2type__erasure.html#autotoc_md109',1,'']]],
  ['configure_20build_20and_20test_29',['Configure Build and Test',['../md_docs_2pages_2developing.html#autotoc_md34',1,'']]],
  ['connection_30',['Creating a Connection',['../md_docs_2pages_2ipc.html#autotoc_md86',1,'']]],
  ['connection_20management_31',['Connection Management',['../md_docs_2pages_2ipc.html#autotoc_md83',1,'']]],
  ['consuming_20via_20cmake_32',['Consuming via CMake',['../md_docs_2pages_2build.html#autotoc_md15',1,'']]],
  ['consuming_20via_20flake_33',['Consuming via Flake',['../md_docs_2pages_2build.html#autotoc_md21',1,'']]],
  ['container_20customizations_34',['Intrusive Container Customizations',['../md_docs_2pages_2intrusive.html#autotoc_md75',1,'']]],
  ['containers_35',['Containers',['../md_docs_2pages_2allocator.html#autotoc_md10',1,'Allocator Interaction with Containers'],['../md_docs_2pages_2intrusive.html#autotoc_md73',1,'Comparison with Owning Containers'],['../md_docs_2pages_2intrusive.html',1,'Intrusive Containers'],['../md_docs_2pages_2intrusive.html#autotoc_md74',1,'Main Concern with Intrusive Containers']]],
  ['contents_36',['Table of Contents',['../md_docs_2pages_2library__component__overview.html#autotoc_md90',1,'']]],
  ['coroutines_37',['Async RAII in Coroutines',['../md_docs_2pages_2execution.html#autotoc_md58',1,'']]],
  ['counting_20scope_38',['Counting Scope',['../md_docs_2pages_2execution.html#autotoc_md63',1,'']]],
  ['coverage_39',['&lt;span class=&quot;tt&quot;&gt;coverage&lt;/span&gt;',['../md_docs_2pages_2developing.html#autotoc_md36',1,'']]],
  ['cpos_40',['Expressivity for complex CPOs',['../md_docs_2pages_2type__erasure.html#autotoc_md111',1,'']]],
  ['creating_20a_20connection_41',['Creating a Connection',['../md_docs_2pages_2ipc.html#autotoc_md86',1,'']]],
  ['creating_20the_20type_20erased_20operation_20state_20fails_42',['Case 3: Creating the Type-Erased Operation State Fails',['../md_docs_2pages_2execution.html#autotoc_md70',1,'']]],
  ['creating_20the_20type_20erased_20receiver_20fails_43',['Case 1: Creating the Type-Erased Receiver Fails',['../md_docs_2pages_2execution.html#autotoc_md68',1,'']]],
  ['creating_20the_20type_20erased_20sender_20fails_44',['Case 2: Creating the Type-Erased Sender Fails',['../md_docs_2pages_2execution.html#autotoc_md69',1,'']]],
  ['custom_20deserialization_20formats_45',['Custom Deserialization Formats',['../md_docs_2pages_2serialization.html#autotoc_md95',1,'']]],
  ['custom_20serialization_20formats_46',['Custom Serialization Formats',['../md_docs_2pages_2serialization.html#autotoc_md94',1,'']]],
  ['customizations_47',['Intrusive Container Customizations',['../md_docs_2pages_2intrusive.html#autotoc_md75',1,'']]]
];
